config/routes.rb
FullcalendarAssets::Application.routes.draw do  resource :calendar, :only => [:show]

  devise_for :users

  resources :events, :api

  match 'auth/:provider/callback', :to => 'authentications#create'
  match 'auth/failure', to: redirect('/')

  root :to => 'home#index'

  match 'tagged' => 'events#tagged', :as => 'tagged'

end

app/models/api.rb
class Api < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base

  scope :between, lambda {|start_time, end_time|
    {:conditions => ["? < starts_at < ?", Event.format_date(start_time), Event.format_date(end_time)] }
  }

  #Used to enable tagging
  acts_as_taggable
  acts_as_taggable_on :tags
  #attr_accessible :tag_list


  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :tags => self.tags || "",
      :allDay => self.all_day,
      :recurring => false,
      :color => self.color || "#FCFE75",
      :url => Rails.application.routes.url_helpers.event_path(id),
      #:color => "red"
    }

  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  # :confirmable,
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  respond_to :json
  require 'json'

  def index
  	respond_with(@events = Event.all, :status => :ok)
  end

  def show
    respond_with(:status => :ok)
  end

  def create
  	event_data = JSON.parse(params[:data].gsub("'", '"'))
  	@event = Event.new(event_data.first)
  	@event.save
	render :text => "ok"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
  end
  
  def create
    auth = request.env["omniauth.auth"] 
    current_user.authentications.create(:provider => auth['provider'], :uid => auth['uid'])
    flash[:notice] = "Authentication successful."
    redirect_to authentications_url
  end
  
  def destroy
  end
end
=begin
class AuthenticationsController < ApplicationController
  def index
    @authentications = Authentication.all
  end

  def create
    @authentication = Authentication.new(params[:authentication])
    if @authentication.save
      redirect_to authentications_url, :notice => "Successfully created authentication."
    else
      render :action => 'new'
    end
  end

  def destroy
    @authentication = Authentication.find(params[:id])
    @authentication.destroy
    redirect_to authentications_url, :notice => "Successfully destroyed authentication."
  end
end
=end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def show
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.scoped
    @events = Event.between(params['start'], params['end']) if (params['start'] && params['end'])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def tagged
    @events = Event.scoped
    @events = Event.tagged_with(params[:tag])
    respond_to do |format|
      format.html 
      format.json { render :json => @events }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 def index
   if user_signed_in?
     redirect_to calendar_path
   end
   #redirect_to http://localhost:3000/auth/yammer/callback
 end
 
end
 

app/controllers/logfiles_controller.rb
class LogfilesController < ApplicationController

  # GET /logfiles
  # GET /logfiles.json
  def index
    @logfiles = Logfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logfiles }
    end
  end

  # GET /logfiles/1
  # GET /logfiles/1.json
  def show
    @logfile = Logfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @logfile }
    end
  end

  # GET /logfiles/new
  # GET /logfiles/new.json
  def new
    @logfile = Logfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @logfile }
    end
  end

  # GET /logfiles/1/edit
  def edit
    @logfile = Logfile.find(params[:id])
  end

  # POST /logfiles
  # POST /logfiles.json
  def create
    @logfile = Logfile.new(params[:logfile])
    file_data = params[:logfile]
    if file_data.respond_to?(:read)
      json_contents = file_data.read
    elsif file_data.respond_to?(:path)
      json_contents = File.read(file_data.path)
    else
      logger.error "Bad file_data: #{file_data.class.name}: #{file_data.inspect}"
    end

    respond_to do |format|
      if @logfile.save
        format.html { redirect_to @logfile, notice: 'Logfile was successfully created.' }
        format.json { render json: @logfile, status: :created, location: @logfile }
      else
        format.html { render action: "new" }
        format.json { render json: @logfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logfiles/1
  # PUT /logfiles/1.json
  def update
    @logfile = Logfile.find(params[:id])

    respond_to do |format|
      if @logfile.update_attributes(params[:logfile])
        format.html { redirect_to @logfile, notice: 'Logfile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @logfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logfiles/1
  # DELETE /logfiles/1.json
  def destroy
    @logfile = Logfile.find(params[:id])
    @logfile.destroy

    respond_to do |format|
      format.html { redirect_to logfiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/logfiles_helper.rb
module LogfilesHelper
end

app/views/authentications/index.html.erb
<% title "Authentications" %>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td><%= authentication.user_id %></td>
      <td><%= authentication.provider %></td>
      <td><%= authentication.uid %></td>
      <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/calendars/show.html.erb
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as: <%= current_user.email %>.<br/>
    Not you? <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>
<br/>
<div id='calendar'></div>
<br/><br/><br/>


<%= link_to t('.new_event', :default => t("helpers.links.new_event")),
              new_event_path, :class => 'btn btn-large btn-success' %>
<%= link_to t('.all_events', :default => t("helpers.links.all_events")),
              events_path, :class => 'btn btn-large' 				%>      
<br/><br/>
<!-- Used to display Netapp info from Yammer. TODO: replace with more meaningful data... 
<script data-app-id="hyB2pTvrL36Y50py8EWj6A"
src="https://assets.yammer.com/platform/yam.js"></script>
<script> yam.connect.embedFeed({
	container: "#embedded-feed",
	network: "netapp.com"});
</script>
<div id="embedded-feed"></div>
-->

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :starts_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :starts_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ends_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :ends_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :all_day, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :all_day, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :color, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :color, [['Green','#A1FA7E'],['Yellow','#FCFE75'],['Red','#FD8B8B'],['Blue','#A1A6FB']] %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area', :size => '30x5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tag_list, "Tags (separated by commas)" %>
    <div class="controls">
      <%= f.text_field :tag_list %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit This %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:starts_at) %></th>
      <th><%= model_class.human_attribute_name(:ends_at) %></th>
      <th><%= model_class.human_attribute_name(:all_day) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr bgcolor=<%=event.color%>>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= link_to event.title, event_path(event) %></td>
        <td><%= event.starts_at %></td>
        <td><%= event.ends_at %></td>
        <td><%= event.all_day %></td>
        <td><%= event.description %></td>
        <td><% event.tags.any? %>
            <% event.tags.each do |tag| %>
                <%= link_to tag.name, tagged_url(:tag => tag.name) %>
            <% end%>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new_event', :default => t("helpers.links.new_event")),
            new_event_path,
            :class => 'btn btn-success' %>
<%= link_to t('.back_to_calendar', :default => t("helpers.links.back_to_calendar")),
            calendar_path,
            :class => 'btn' %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @event.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:starts_at) %>:</strong></dt>
  <dd><%= @event.starts_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ends_at) %>:</strong></dt>
  <dd><%= @event.ends_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:all_day) %>:</strong></dt>
  <dd><%= @event.all_day %></dd>
  <dt><strong><%= model_class.human_attribute_name(:color) %>:</strong></dt>
  <dd><%= @event.color %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd>
  <% @event.tags.any? %>
    <% @event.tags.each do |tag| %>
      <%= link_to tag.name, tagged_url(:tag => tag.name) %>
    <% end%>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/events/tagged.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%= "Events Tagged With: '#{params[:tag]}'" %></h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:starts_at) %></th>
      <th><%= model_class.human_attribute_name(:ends_at) %></th>
      <th><%= model_class.human_attribute_name(:all_day) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr bgcolor=<%=event.color%>>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= link_to event.title, event_path(event) %></td>
        <td><%= event.starts_at %></td>
        <td><%= event.ends_at %></td>
        <td><%= event.all_day %></td>
        <td><%= event.description %></td>
        <td><% event.tags.any? %>
            <% event.tags.each do |tag| %>
                <%= link_to tag.name, tagged_url(:tag => tag.name) %>
            <% end%>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new_event', :default => t("helpers.links.new_event")),
            new_event_path,
            :class => 'btn btn-success' %>
<%= link_to t('.back_to_calendar', :default => t("helpers.links.back_to_calendar")),
            calendar_path,
            :class => 'btn' %>

app/views/home/index.html.erb
<h1>Welcome to SunDial!</h1>
<br/>
<br/>
<br/>
<br/>
<%= link_to t('.my_calendar', :default => t("helpers.links.my_calendar")),
            calendar_path,
            :class => 'btn btn-large' %>
<%= link_to t('.login', :default => t("helpers.links.login_or_sign_up")),
            new_user_session_path,
            :class => 'btn btn-large' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SunDial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>